app/page/urls.py
# app/page/urls.py

# Django and third parties modules
from django.urls import path

# Locals
from app.page.views import home_view

app_name = 'page'

urlpatterns = [

    path('', home_view, name='home'),

]

app/user_profile/urls.py
# app/user_profile/urls.py

# Django and third parties modules
from django.urls import path

# Locals
from app.user_profile.views import login_view, logout_view, register_view

app_name = 'user_profile'

urlpatterns = [

    path('login/', login_view, name='login'),
    path('register/', register_view, name='register'),
    path('logout/', logout_view, name='logout'),

]

config/urls.py
# config/urls.py

"""
https://docs.djangoproject.com/en/4.2/topics/http/urls/
"""
from django.contrib import admin
from django.urls import path, include

urlpatterns = [

    # user_profile
    path('user/', include('app.user_profile.urls', namespace='user_profile')),

    # page
    path('', include('app.page.urls', namespace='page')),

    # admin
    path('admin/', admin.site.urls),
]

app/user_profile/models.py
from django.db import models

# Create your models here.

app/page/views.py
# app/page/views.py

# Django and third parties modules
from django.shortcuts import render

# Locals

# Create your views here.

def home_view(request):
	return render(request, 'page/home_page.html')

app/user_profile/views.py
# # app/user_profile/views.py

from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import render, redirect

# # Locals

# # Create your views here.

# USER LOGIN
def login_view(request):
	# Let the logged in user go directly to the home page.
	if request.user.is_authenticated:
		messages.info(request, f'{request.user.username } You Have Already Login ;)')
		return redirect('page:home')

	context = dict()

	if request.method == "POST":
		# print(request.POST)
		username = request.POST.get('username')
		password = request.POST.get('password')
		# print(username, password)
		
		if len(username) < 6 or len(password) < 6:
			messages.warning(request, f'Please Enter the Username and Password Correctly.. It must not be less than 6 characters..')
			return redirect('user_profile:login')

		user = authenticate(request, username=username, password=password)

		if user is not None:
			login(request, user)
			messages.success(request, f'{request.user.username } You are logged in')
			return redirect('page:home')
			
	return render(request, 'user_profile/login.html', context)


# USER LOGOUT
def logout_view(request):
	messages.info(request, f'{request.user.username} Signed Out')
	logout(request)
	return redirect('page:home')


# USER REGISTER
def register_view(request):
	
	context = dict()

	if request.method == 'POST':
		print(request.POST)

	return render(request, 'user_profile/register.html', context)

app/user_profile/templates/user_profile/login.html
{% extends 'base_without_navbar.html' %}

{% block content %}

<div class="container mt-5">
    <div class="row">
        <div class="col-sm-6 offset-sm-3">
            <h1>Login:</h1>
            <form method="post">
                {% csrf_token %}
                <!-- don't forget to specify the method in the form! If it won't show up in the search, the method should be POST. -->
                <!-- every input information must be a name information!.. -->
                <!-- Must have csrf token information.. -->
                <div class="mb-3">
                    <label for="exampleInputEmail1" class="form-label">Username</label>
                    <input 
                        type="text" 
                        class="form-control" 
                        id="exampleInputEmail1" aria-describedby="emailHelp" 
                        name="username">
                </div>
                <div class="mb-3">
                    <label for="exampleInputPassword1" class="form-label">Password</label>
                    <input 
                        type="password" 
                        class="form-control" 
                        id="exampleInputPassword1" 
                        name="password">
                </div>
                <button type="submit" class="btn btn-primary">Login</button>
            </form>
        </div>
    </div>
</div>
{% endblock content %}

app/user_profile/templates/user_profile/register.html
{% extends 'base_without_navbar.html' %}

{% block content %}

<div class="container mt-5">
    <div class="row">
        <div class="col-sm-6 offset-sm-3">
            <h1>Sign up:</h1>
            <form method="post">
                {% csrf_token %}
                <!-- don't forget to specify the method in the form! If it won't show up in the search, the method should be POST. -->
                <!-- every input information must be a name information!.. -->
                <!-- Must have csrf token information.. -->

                <div class="mb-3">
                    <label for="first_name" class="form-label">Name</label>
                    <input 
                        type="text" 
                        class="form-control" 
                        id="first_name" 
                        name="first_name">
                </div>

                <div class="mb-3">
                    <label for="last_name" class="form-label">Surname</label>
                    <input 
                        type="text" 
                        class="form-control" 
                        id="last_name" 
                        name="last_name">
                </div>

                <div class="mb-3">
                    <label for="email" class="form-label">Email</label>
                    <input 
                        type="email" 
                        class="form-control" 
                        id="email" 
                        aria-describedby="emailHelp" 
                        name="email">
                </div>
                <div class="mb-3">
                    <label for="email-confirm" class="form-label">Email - Repeat</label>
                    <input 
                        type="email" 
                        class="form-control" 
                        id="email-confirm" 
                        aria-describedby="emailHelp" 
                        name="email-confirm">
                </div>
                <div class="mb-3">
                    <label for="password" class="form-label">Password</label>
                    <input 
                        type="password" 
                        class="form-control" 
                        id="password" 
                        name="password">
                </div>
                <div class="mb-3">
                    <label for="password-confirm" class="form-label">Password - Repeat</label>
                    <input 
                        type="password" 
                        class="form-control" 
                        id="password-confirm" 
                        name="password-confirm">
                </div>

                <div class="mb-3">
                    <label for="instagram" class="form-label">Instagram Account</label>
                    <input 
                        type="text" 
                        class="form-control" 
                        id="instagram" 
                        name="instagram">
                </div>
                <button 
                    type="submit" 
                    class="btn btn-primary">Sign up</button>
                <a 
                    href="{% url 'page:home' %}" 
                    class="btn btn-secondary">Cancel</a>
                <a 
                    href="{% url 'user_profile:login' %}" 
                    class="btn btn-info">Login</a>
            </form>
        </div>
    </div>
</div>
{% endblock content %}

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>MD Clone | {% block title %}{{block.super}}{% endblock title %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>

    <!-- MESSAGE -->
    {% include 'messages.html' %}
    <!-- MESSAGE -->

    <!-- NAVBAR -->
    {% include 'navbar.html'%}
    <!-- NAVBAR END -->

    {% block content %}
    {% endblock content %}

    
    <!-- NAVBAR-Footer -->
    {% include 'footer.html'%}
    <!-- NAVBAR-Footer END -->

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8"
        crossorigin="anonymous"></script>
</body>
</html>

templates/base_without_navbar.html
{% load static %}
<!doctype html>
<html lang="tr">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>MD Clone</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
    
    {% include 'messages.html' %}
    
    {% block content %}
    {% endblock content %}
    
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
</body>

</html>

templates/footer.html
{% load static %}

    <nav class="navbar navbar-expand-lg bg-warning border-bottom border-dark">
        <div class="container py-2">
            <a class="navbar-brand" href="#">MD Clone</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup"
                aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                <div class="navbar-nav ms-auto">
                    <a class="nav-link" aria-current="page" href="#">
                    Our story
                    </a>
                    <a class="nav-link" href="#">
                    Membership
                    </a>
                    <a class="nav-link" href="#">Write</a>
                    <a class="nav-link" href="#">Sign In</a>
                    <a class="nav-link btn btn-dark text-light px-3 rounded-pill ms-3">Get Started</a>
                </div>
            </div>
        </div>
    </nav>

templates/messages.html
<!-- https://docs.djangoproject.com/en/4.1/ref/contrib/messages/ -->

{% if messages %}
    {% for message in messages %}
    <div 
        class="alert alert-{{ message.tags }} alert-dismissible fade show" 
        role="alert">
        <strong>{{ message }} </strong>
        <button 
            type="button" 
            class="btn-close" 
            data-bs-dismiss="alert" 
            aria-label="Close"></button>
    </div>
    {% endfor %}
{% endif %}

templates/navbar.html
{% load static %}

    <nav class="navbar navbar-expand-lg bg-warning border-bottom border-dark">
        <div class="container py-2">
            <a class="navbar-brand" href="#">MD Clone</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup"
                aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                <div class="navbar-nav ms-auto">
                    <a class="nav-link" aria-current="page" href="#">
                    Our story
                    </a>
                    <a class="nav-link" href="#">
                    Membership
                    </a>
                    <a class="nav-link" href="#">Write</a>
                    {% if not request.user.is_authenticated %}
                    <a class="nav-link" href="{% url 'user_profile:login' %}">
                        Sign In
                    </a>
                    <a class="nav-link btn btn-dark text-light px-3 rounded-pill ms-3"
                        href="{% url 'user_profile:register' %}">
                        Get Started
                    </a>
                    {% else %}
                    <a class="nav-link" href="#">{{ request.user.username }}</a>
                    <a class="nav-link btn btn-dark text-light px-3 rounded-pill ms-3"
                        href="{% url 'user_profile:logout' %}">
                        Logout
                    </a>
                    {% endif %}
                </div>
            </div>
        </div>
    </nav>